# Generated by Django 3.2.15 on 2022-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductDescription', models.CharField(max_length=500)),
                ('ProductRemark', models.CharField(max_length=500)),
                ('ProductDocument', models.FileField(upload_to='pdf')),
                ('ProductVideo', models.URLField(max_length=500)),
                ('ProductSource', models.URLField(max_length=500)),
                ('productDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HScode',
            fields=[
                ('HsId', models.AutoField(primary_key=True, serialize=False)),
                ('HsCode', models.IntegerField()),
                ('HsDescription', models.CharField(max_length=500)),
                ('HsRemark', models.CharField(max_length=500)),
                ('HsDocument', models.FileField(upload_to='pdf')),
                ('HsVideo', models.URLField(max_length=500)),
                ('HsSource', models.URLField(max_length=500)),
                ('HsDate', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='TaskApp1.Product')),
            ],
        ),
    ]
