# Generated by Django 3.2.15 on 2022-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp1', '0002_auto_20220814_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductDocument',
            field=models.FileField(upload_to='.pdf/'),
        ),
    ]
